components:
  schemas:
    HealthCheck:
      description: Response model to validate and return when performing a health
        check.
      properties:
        status:
          default: OK
          title: Status
          type: string
        status_code:
          default: 200
          title: Status Code
          type: integer
      title: HealthCheck
      type: object
info:
  description: Generate ads for your business
  title: Ad Generator
  version: 0.0.1
openapi: 3.1.0
paths:
  /:
    get:
      description: Base route of the python_template API.
      operationId: main_route__get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Main Route
      tags:
      - base
  /health:
    get:
      description: "## Perform a Health Check\nEndpoint to perform a healthcheck on.\
        \ This endpoint can primarily be used Docker\nto ensure a robust container\
        \ orchestration and management is in place. Other\nservices which rely on\
        \ proper functioning of the API service will not deploy if this\nendpoint\
        \ returns any other HTTP status code except 200 (OK).\nReturns:\n    HealthCheck:\
        \ Returns a JSON response with the health status"
      operationId: get_health_health_get
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheck'
          description: Return HTTP Status Code 200 (OK)
      summary: Perform a Health Check
      tags:
      - healthcheck
      - healthcheck
